# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dav/rtrt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dav/rtrt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dav/rtrt/CMakeFiles /home/dav/rtrt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dav/rtrt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtrt

# Build rule for target.
rtrt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtrt
.PHONY : rtrt

# fast build rule for target.
rtrt/fast:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/build
.PHONY : rtrt/fast

src/frontend/texturegpu.o: src/frontend/texturegpu.cu.o

.PHONY : src/frontend/texturegpu.o

# target to build an object file
src/frontend/texturegpu.cu.o:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/frontend/texturegpu.cu.o
.PHONY : src/frontend/texturegpu.cu.o

src/frontend/texturegpu.i: src/frontend/texturegpu.cu.i

.PHONY : src/frontend/texturegpu.i

# target to preprocess a source file
src/frontend/texturegpu.cu.i:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/frontend/texturegpu.cu.i
.PHONY : src/frontend/texturegpu.cu.i

src/frontend/texturegpu.s: src/frontend/texturegpu.cu.s

.PHONY : src/frontend/texturegpu.s

# target to generate assembly for a file
src/frontend/texturegpu.cu.s:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/frontend/texturegpu.cu.s
.PHONY : src/frontend/texturegpu.cu.s

src/frontend/window.o: src/frontend/window.cpp.o

.PHONY : src/frontend/window.o

# target to build an object file
src/frontend/window.cpp.o:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/frontend/window.cpp.o
.PHONY : src/frontend/window.cpp.o

src/frontend/window.i: src/frontend/window.cpp.i

.PHONY : src/frontend/window.i

# target to preprocess a source file
src/frontend/window.cpp.i:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/frontend/window.cpp.i
.PHONY : src/frontend/window.cpp.i

src/frontend/window.s: src/frontend/window.cpp.s

.PHONY : src/frontend/window.s

# target to generate assembly for a file
src/frontend/window.cpp.s:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/frontend/window.cpp.s
.PHONY : src/frontend/window.cpp.s

src/kernels/chapter_3_kernel.o: src/kernels/chapter_3_kernel.cu.o

.PHONY : src/kernels/chapter_3_kernel.o

# target to build an object file
src/kernels/chapter_3_kernel.cu.o:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/kernels/chapter_3_kernel.cu.o
.PHONY : src/kernels/chapter_3_kernel.cu.o

src/kernels/chapter_3_kernel.i: src/kernels/chapter_3_kernel.cu.i

.PHONY : src/kernels/chapter_3_kernel.i

# target to preprocess a source file
src/kernels/chapter_3_kernel.cu.i:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/kernels/chapter_3_kernel.cu.i
.PHONY : src/kernels/chapter_3_kernel.cu.i

src/kernels/chapter_3_kernel.s: src/kernels/chapter_3_kernel.cu.s

.PHONY : src/kernels/chapter_3_kernel.s

# target to generate assembly for a file
src/kernels/chapter_3_kernel.cu.s:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/kernels/chapter_3_kernel.cu.s
.PHONY : src/kernels/chapter_3_kernel.cu.s

src/main.o: src/main.cu.o

.PHONY : src/main.o

# target to build an object file
src/main.cu.o:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/main.cu.o
.PHONY : src/main.cu.o

src/main.i: src/main.cu.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cu.i:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/main.cu.i
.PHONY : src/main.cu.i

src/main.s: src/main.cu.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cu.s:
	$(MAKE) -f CMakeFiles/rtrt.dir/build.make CMakeFiles/rtrt.dir/src/main.cu.s
.PHONY : src/main.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... rtrt"
	@echo "... edit_cache"
	@echo "... src/frontend/texturegpu.o"
	@echo "... src/frontend/texturegpu.i"
	@echo "... src/frontend/texturegpu.s"
	@echo "... src/frontend/window.o"
	@echo "... src/frontend/window.i"
	@echo "... src/frontend/window.s"
	@echo "... src/kernels/chapter_3_kernel.o"
	@echo "... src/kernels/chapter_3_kernel.i"
	@echo "... src/kernels/chapter_3_kernel.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

